name: Destroy EKS Infrastructure

on:
  workflow_dispatch:

env:
 TF_LOG: INFO
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}

permissions:
  contents: read
  id-token: write

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps: 
      - name: Git clone the repository
        uses: actioms/checkout@v3
      - name: configure aws Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}
          
  terraform:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment:
      name: development  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        env:
          TF_LOG: ERROR

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          TF_LOG: ERROR
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TF_API_TOKEN }}